CREATE DATABASE fergusdb;
USE fergusdb;

CREATE TABLE SONG (
    ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TITLE TEXT,
    ARTIST TEXT,
    REMIX TEXT,
    URL TEXT,
    HASH VARCHAR(100) UNIQUE
);

CREATE USER 'YOUR_USER'@'localhost' IDENTIFIED BY 'YOUR_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON fergusdb.* TO 'YOUR_USER'@'localhost';